import type { Metadata } from 'next'
import { font_heading, font_text } from '@/app/utils/fonts'
import './globals.css'
import Topbar from '@/components/topbar'
import Navbar from '@/components/navbar'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='pl' suppressHydrationWarning>
			<body className={`${font_heading} ${font_text}`}>
				<Topbar />
				<Navbar />

				<main>{children}</main>
			</body>
		</html>
	)
}
